version: '3'
services:
  api:
    container_name: API
    build: .
    ports:
      - 8000:8000
    command: uvicorn easydata.main:app --reload --host 0.0.0.0 --port 8000
    restart: always
    env_file: ./easydata/.env
    volumes:
      - .:/EasyData
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - dev

  mongo:
    env_file: ./easydata/.env
    image: mongo
    restart: always
    networks:
      - dev
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - dev
    env_file: ./easydata/.env
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - dev
  celery_beat:
    container_name: celery_beat
    build: .
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A easydata.services.celery beat --loglevel=info
    volumes:
      - .:/EasyData
    env_file: ./easydata/.env
    depends_on:
      - api
      - rabbitmq
      - celery_worker
    networks:
      - dev
  celery_worker:
    container_name: celery_worker
    build: .
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A easydata.services.celery worker --pool=gevent --loglevel=info
    volumes:
      - .:/EasyData
    env_file: ./easydata/.env
    depends_on:
      - api
      - rabbitmq
    networks:
      - dev
  flower:
    image: mher/flower:0.9.5
    restart: "no"
    env_file: ./easydata/.env
    ports:
      - 5555:5555
    depends_on:
      - "celery_worker"
    networks:
      - dev

networks:
  dev: null
