version: '3'
services:
  api:
    container_name: NSA_API
    build: .
    ports:
      - 8000:8000
    command: pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8000
    restart: always
    env_file: ./nsa/.env
    volumes:
      - .:/news-sites-analytics
    depends_on:
      - mongo
    networks:
      - dev

  mongo:
    env_file: ./nsa/.env
    image: mongo
    restart: always
    networks:
      - dev
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - dev
    env_file: ./nsa/.env

networks:
  dev: null
