version: '3'
services:
  api:
    container_name: NSA_API
    build: .
    ports:
      - 8000:8000
    command: pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8000
    restart: always
    env_file: ./nsa/.env
    volumes:
      - .:/news-sites-analytics
    depends_on:
      - mongo
    networks:
      - dev

  mongo:
    env_file: ./nsa/.env
    image: mongo
    restart: always
    networks:
      - dev
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - dev
    env_file: ./nsa/.env
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
  celery_worker:
    container_name: celery_worker
    build: .
    command: pipenv run celery -A nsa.celery.tasks worker --loglevel=info
    volumes:
      - .:/news-sites-analytics
    env_file: ./nsa/.env
    depends_on:
      - api
      - rabbitmq
  celery_beat:
    container_name: celery_beat
    build: .
    command: pipenv run celery -A nsa.celery.tasks beat --loglevel=info
    volumes:
      - .:/news-sites-analytics
    env_file: ./nsa/.env
    depends_on:
      - api
      - rabbitmq
      - celery_worker
networks:
  dev: null
